import { MetadataRoute } from "next";

export const dynamic = "force-static";

/**
 * robots.txt — generated by Next.js from this metadata route.
 *
 * Per AI_VISIBILITY_ACTION_PLAN.md Step 1.5, AI training / search
 * crawlers are EXPLICITLY allowed. The plan's reasoning:
 * "you want AI to know you" — disallowing GPTBot / ClaudeBot /
 * PerplexityBot / etc. removes sabtools.in from the corpus those
 * assistants recommend from. Most sites do this on principle; we
 * deliberately don't, because brand awareness in AI assistants is a
 * primary growth lever for an Indian tools site.
 *
 * AI bots allowed (additions May 2026 per Phase 1 of AI visibility plan):
 *   - GPTBot          (OpenAI training)
 *   - OAI-SearchBot   (ChatGPT browsing)
 *   - Google-Extended (Bard / Gemini training opt-in)
 *   - PerplexityBot   (Perplexity AI search)
 *   - ClaudeBot       (Anthropic Claude — added 2026-05)
 *   - anthropic-ai    (Anthropic legacy UA — added 2026-05)
 *   - CCBot           (Common Crawl — feeds many open-source LLMs; 2026-05)
 *   - Bytespider      (ByteDance / TikTok / Doubao AI — added 2026-05)
 *
 * Crawl-blocked paths (universal):
 *   - /api/         no API routes exist on the static export anyway
 *   - /_next/image/ Next.js' image optimizer endpoint (we serve raw)
 *   - /embed/       embeddable iframe widgets — robots:noindex per page
 *   - /search       client-side search route — no indexable content
 *   - /admin/       reserved future namespace, never indexed
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/", "/_next/image/", "/embed/", "/search", "/admin/"],
      },
      {
        userAgent: "Googlebot",
        allow: ["/", "/_next/static/"],
        disallow: ["/embed/", "/search", "/admin/"],
      },
      { userAgent: "AdsBot-Google", allow: "/" },

      // === AI training & search crawlers — explicitly allowed ===
      // OpenAI
      { userAgent: "GPTBot", allow: "/" },
      { userAgent: "OAI-SearchBot", allow: "/" },
      // Google Bard / Gemini
      { userAgent: "Google-Extended", allow: "/" },
      // Perplexity AI
      { userAgent: "PerplexityBot", allow: "/" },
      // Anthropic Claude — both current and legacy user-agents
      { userAgent: "ClaudeBot", allow: "/" },
      { userAgent: "anthropic-ai", allow: "/" },
      // Common Crawl — feeds many open-source LLM training corpora
      { userAgent: "CCBot", allow: "/" },
      // ByteDance (TikTok / Doubao) AI
      { userAgent: "Bytespider", allow: "/" },
    ],
    sitemap: [
      "https://sabtools.in/sitemap-index.xml",
      "https://sabtools.in/sitemap.xml",
      "https://sabtools.in/sitemap-hi.xml",
    ],
  };
}
