"use client";
import { useState } from "react";

/**
 * Real PDF download using jsPDF + html2canvas-pro.
 *
 * Captures the .result-card element(s) on the page, renders them onto a
 * branded SabTools PDF (header + footer with sabtools.in URL + date), and
 * downloads. Falls back to window.print() if no result is on screen yet
 * (e.g. user hits Download before entering inputs).
 */
export default function DownloadPDF({
  toolName = "Calculation",
}: {
  toolName?: string;
} = {}) {
  const [busy, setBusy] = useState(false);

  const handleDownload = async () => {
    if (busy) return;
    setBusy(true);

    try {
      // Find result content. Most tools wrap their result in `.result-card`.
      const card = document.querySelector(".result-card") as HTMLElement | null;

      if (!card) {
        // No result rendered yet → fall back to native print.
        window.print();
        return;
      }

      // Lazy-load heavy libs only when the user clicks (zero first-paint cost)
      const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
        import("jspdf"),
        import("html2canvas-pro"),
      ]);

      // Render the result card to a canvas at 2x for retina
      const canvas = await html2canvas(card, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: "#ffffff",
      });

      const imgData = canvas.toDataURL("image/png");

      // A4 portrait: 210 × 297 mm
      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 12;

      // === Branded header ===
      pdf.setFillColor(79, 70, 229); // indigo-600
      pdf.rect(0, 0, pageWidth, 18, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(14);
      pdf.setFont("helvetica", "bold");
      pdf.text("SabTools.in", margin, 12);
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "normal");
      pdf.text("Free Online Tools — No Signup Required", pageWidth - margin, 12, {
        align: "right",
      });

      // === Title ===
      pdf.setTextColor(17, 24, 39); // gray-900
      pdf.setFontSize(15);
      pdf.setFont("helvetica", "bold");
      pdf.text(toolName, margin, 30);

      // === Subtitle: date + URL ===
      pdf.setFontSize(9);
      pdf.setTextColor(107, 114, 128); // gray-500
      pdf.setFont("helvetica", "normal");
      const dateStr = new Date().toLocaleDateString("en-IN", {
        weekday: "long",
        year: "numeric",
        month: "long",
        day: "numeric",
      });
      pdf.text(`Generated on ${dateStr}`, margin, 36);
      // Also include the page URL so the recipient can re-open the calculation
      const url = typeof window !== "undefined" ? window.location.href : "https://sabtools.in";
      pdf.text(`URL: ${url}`, margin, 41);

      // === Image of the result card ===
      const usableWidth = pageWidth - 2 * margin;
      const aspectRatio = canvas.height / canvas.width;
      let imgHeight = usableWidth * aspectRatio;
      const startY = 48;
      const usableHeight = pageHeight - startY - 18; // leave 18mm for footer

      // If image taller than one page, scale down to fit one page.
      // (Multi-page handling adds complexity — most tool results fit on one page.)
      if (imgHeight > usableHeight) {
        imgHeight = usableHeight;
      }
      const renderWidth = imgHeight / aspectRatio;
      const xOffset = margin + (usableWidth - renderWidth) / 2;
      pdf.addImage(imgData, "PNG", xOffset, startY, renderWidth, imgHeight);

      // === Footer ===
      pdf.setDrawColor(229, 231, 235); // gray-200
      pdf.line(margin, pageHeight - 14, pageWidth - margin, pageHeight - 14);
      pdf.setFontSize(8);
      pdf.setTextColor(107, 114, 128);
      pdf.text(
        "Generated by sabtools.in — calculations are estimates, not financial / legal advice.",
        margin,
        pageHeight - 8
      );
      pdf.text(`Page 1`, pageWidth - margin, pageHeight - 8, { align: "right" });

      // === Save ===
      const safeName = toolName.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
      pdf.save(`sabtools-${safeName}-${Date.now()}.pdf`);
    } catch (err) {
      console.error("PDF generation failed, falling back to print:", err);
      window.print();
    } finally {
      setBusy(false);
    }
  };

  return (
    <button
      onClick={handleDownload}
      disabled={busy}
      className="download-pdf-btn inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-indigo-500 to-purple-500 text-white text-sm font-semibold shadow-sm hover:shadow-md hover:from-indigo-600 hover:to-purple-600 transition-all duration-200 hover:-translate-y-0.5 disabled:opacity-60 disabled:cursor-wait"
      title="Download results as a branded PDF"
    >
      {busy ? (
        <>
          <svg className="animate-spin" width="16" height="16" viewBox="0 0 24 24" fill="none">
            <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="3" opacity="0.25" />
            <path
              d="M22 12a10 10 0 0 0-10-10"
              stroke="currentColor"
              strokeWidth="3"
              strokeLinecap="round"
            />
          </svg>
          Generating…
        </>
      ) : (
        <>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
            <polyline points="7 10 12 15 17 10" />
            <line x1="12" y1="15" x2="12" y2="3" />
          </svg>
          Download as PDF
        </>
      )}
    </button>
  );
}
