/**
 * ResponsiveImage — `<picture>` wrapper that serves AVIF + WebP responsive
 * variants generated by `scripts/optimize-images.mjs` at build time.
 *
 * For a source like `/blog/foo.webp`, the optimizer emits:
 *   /blog/foo-w320.{webp,avif}   (mobile)
 *   /blog/foo-w768.{webp,avif}   (tablet)
 *   /blog/foo-w1200.{webp,avif}  (desktop)
 *
 * The browser picks the smallest format it understands at the smallest
 * matching size. Modern Chrome / Safari / Firefox pick AVIF (40-60%
 * smaller than WebP). Older browsers fall through to WebP, then to the
 * raw <img src> as a final fallback.
 *
 * Server Component (no client JS). Drop-in replacement for any plain
 * <img src="/blog/...">.
 *
 * Added by the technical-SEO audit (Fix 5).
 */

interface ResponsiveImageProps {
  /** Source path (e.g. "/blog/foo.webp"). The base name, not a variant. */
  src: string;
  alt: string;
  width: number;
  height: number;
  className?: string;
  /** When true, eagerly loaded + fetchpriority=high — use for hero images
   *  above the fold. Defaults to lazy / async. */
  priority?: boolean;
  /** Optional `sizes` override. Defaults sensibly to a full-width then
   *  capped-to-1200px breakpoint, matching most blog-hero layouts. */
  sizes?: string;
}

const DEFAULT_SIZES = "(max-width: 768px) 100vw, 1200px";

export default function ResponsiveImage({
  src,
  alt,
  width,
  height,
  className,
  priority = false,
  sizes = DEFAULT_SIZES,
}: ResponsiveImageProps) {
  // Strip the extension to derive the variant base path.
  // Match common image extensions only — guard against odd inputs.
  const m = src.match(/^(.*)\.(png|jpe?g|webp|gif)$/i);
  const base = m ? m[1] : src;

  const widths = [320, 768, 1200] as const;
  const buildSrcSet = (fmt: "avif" | "webp") =>
    widths.map((w) => `${base}-w${w}.${fmt} ${w}w`).join(", ");

  return (
    <picture>
      <source type="image/avif" srcSet={buildSrcSet("avif")} sizes={sizes} />
      <source type="image/webp" srcSet={buildSrcSet("webp")} sizes={sizes} />
      <img
        src={`${base}-w1200.webp`}
        alt={alt}
        width={width}
        height={height}
        className={className}
        loading={priority ? "eager" : "lazy"}
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        {...({ fetchpriority: priority ? "high" : "auto" } as any)}
        decoding="async"
      />
    </picture>
  );
}
